name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run'
        required: false
        type: boolean
        default: false
      debug:
        description: 'Debug mode'
        required: false
        type: boolean
        default: false
      releaseType:
        description: 'Release type'
        required: false
        type: choice
        options:
          - stable
          - alpha
          - beta
          - rc
        default: stable

permissions:
  contents: read

env:
  HUSKY: 0

jobs:
  release:
    if: github.event_name == 'workflow_dispatch' && github.actor == 'pplancq'
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: pplancq/actions/setup-node@b248bd44a83e2d0c9f9334aff7e33771fdd77c76 # v1.1.2
        with:
          use-mise: true

      - name: Install package
        run: npm ci --ignore-scripts

      - name: Config npm
        run: |
          npm config set access=public
          npm config set provenance=true

      - name: Build nx release plugin
        run: npm run build --workspace @pplancq/nx-release-plugin

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
        run: |
          ARGS=""
          if [ "${{ github.event.inputs.dryRun }}" = "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          if [ "${{ github.event.inputs.debug }}" = "true" ]; then
            ARGS="$ARGS --verbose"
          fi
          if [ "${{ github.event.inputs.releaseType }}" != "stable" ]; then
            ARGS="$ARGS --preid=${{ github.event.inputs.releaseType }}"
          fi
          npx nx release $ARGS
